runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: continual-works-300118/index.html
  upload: continual-works-300118/index.html

- url: /(.*)
  static_files: continual-works-300118/\1
  upload: continual-works-300118/(.*)
